[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
betinco = "2ZZGJxn8H7uoyJ1WmWbUkc5wqEEBpXuDM3TvXC8rCH7Q"
inco_lightning = "5sjEbPiqgZrYwR31ahR6Uk9wf5awoX61YGg7jExQSwaj"

[programs.localnet]
betinco = "2ZZGJxn8H7uoyJ1WmWbUkc5wqEEBpXuDM3TvXC8rCH7Q"
inco_lightning = "5sjEbPiqgZrYwR31ahR6Uk9wf5awoX61YGg7jExQSwaj"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-market = "npx ts-node scripts/init_market.ts"
